# UPDATED config for teamplate update 2025
irrigation_unlimited:
  controllers:
    - name: "Morning_set"
      enabled: false
      entity_id: "switch.tasmota3_1" # main valve
      all_zones_config: # <= Add these three lines <─┐
        show: # <= to the configuration            <─┤
          timeline: true # <= for all zones        <─┘
      preamble: "00:01"
      zones:
        #- zone_id: 1
        - name: "Watering_right1"
          entity_id: "switch.tasmota1_3"
        - name: "Watering_right2"
          entity_id: "switch.tasmota1_2"
        - name: "Watering_drop_fruts"
          entity_id: "switch.tasmota1_1"
        - name: "Watering_drop_back"
          entity_id: "switch.tasmota1_4"
        - name: "Watering_front"
          entity_id: "switch.tasmota2_1"
        - name: "Watering_drop_left"
          entity_id: "switch.tasmota2_2"
        - name: "Watering_back1"
          entity_id: "switch.tasmota2_3"
        - name: "Watering_back2"
          entity_id: "switch.tasmota2_4"
      sequences:
        - name: "Sequences_morning"
          delay: "00:01"
          enabled: true
          #  repeat: 2
          schedules:
            #    start_n_days: now()
            #    every_n_days: 4
            #- time: "05:00" - for 5 AM
            time:
              sun: "sunrise"
              before: "00:15"
            anchor: finish
            day:
              every_n_days: 1
              start_n_days: 2023-05-13 # Starting date + 1
          zones:
            # Session 1
            - zone_id: 1
              duration: "00:09"
              #repeat: 2
            - zone_id: 2
              duration: "00:09"
              #repeat: 2
            ##            - zone_id: [3,6]
            ##              duration: "00:10"
            #repeat: 2
            ##            - zone_id: 4
            ##              duration: "00:10"
            #repeat: 3
            - zone_id: 5
              duration: "00:12"
              #repeat: 2
            ##            - zone_id: 6
            ##              duration: "00:05"
            ##              #repeat: 2
            - zone_id: 7
              duration: "00:12"
              #repeat: 3
            - zone_id: 8
              duration: "00:17"
              #repeat: 3
            # Session 2
            - zone_id: 1
              duration: "00:09"
              #repeat: 2
            - zone_id: 2
              duration: "00:09"
              #repeat: 2
            ##            - zone_id: [3, 6]
            ##              duration: "00:10"
            #repeat: 2
            ##            - zone_id: 4
            ##              duration: "00:10"
            #repeat: 3
            - zone_id: 5
              duration: "00:12"
              #repeat: 2
            ##            - zone_id: 6
            ##              duration: "00:05"
            ##              #repeat: 2
            - zone_id: 7
              duration: "00:12"
              #repeat: 3
            - zone_id: 8
              duration: "00:17"
              #repeat: 3
            # Session 3
            ##            - zone_id: 4
            ##              duration: "00:07"
            ##              #repeat: 3
            ##- zone_id: 8
            ##  duration: "00:17"
            ##  #repeat: 3
            ##- zone_id: 7
            ##  duration: "00:12"
            ##  #repeat: 3
    - name: "Evening_set"
      enabled: true
      entity_id: "switch.tasmota3_1" # main valve
      all_zones_config: # <= Add these three lines <─┐
        show: # <= to the configuration            <─┤
          timeline: true # <= for all zones        <─┘
      preamble: "00:01"
      zones:
        #- zone_id: 1
        - name: "Watering_right1"
          entity_id: "switch.tasmota1_3"
        - name: "Watering_right2"
          entity_id: "switch.tasmota1_2"
        - name: "Watering_drop_fruts"
          entity_id: "switch.tasmota1_1"
        - name: "Watering_drop_back"
          entity_id: "switch.tasmota1_4"
        - name: "Watering_front"
          entity_id: "switch.tasmota2_1"
        - name: "Watering_drop_left"
          entity_id: "switch.tasmota2_2"
        - name: "Watering_back1"
          entity_id: "switch.tasmota2_3"
        - name: "Watering_back2"
          entity_id: "switch.tasmota2_4"
      sequences:
        - name: "Sequences_evening"
          delay: "00:01"
          enabled: true
          #  repeat: 2
          schedules:
            #    start_n_days: now()
            #    every_n_days: 4
            #- time: "05:00" - for 5 AM
            time:
              sun: "sunset"
              after: "00:15"
            day:
              every_n_days: 1
              start_n_days: 2023-05-13 # Starting date + 1
          zones:
            # Session 1
            - zone_id: 1
              duration: "00:09"
              #repeat: 2
            - zone_id: 2
              duration: "00:09"
              #repeat: 2
            ##            - zone_id: [3,6]
            ##              duration: "00:10"
            #repeat: 2
            ##            - zone_id: 4
            ##              duration: "00:10"
            #repeat: 3
            - zone_id: 5
              duration: "00:12"
              #repeat: 2
            ##            - zone_id: 6
            ##              duration: "00:05"
            ##              #repeat: 2
            - zone_id: 7
              duration: "00:12"
              #repeat: 3
            - zone_id: 8
              duration: "00:17"
              #repeat: 3
            # Session 2
            - zone_id: 1
              duration: "00:09"
              #repeat: 2
            - zone_id: 2
              duration: "00:09"
              #repeat: 2
            ##            - zone_id: [3, 6]
            ##              duration: "00:10"
            ##              #repeat: 2
            ##            - zone_id: 4
            ##              duration: "00:10"
            #repeat: 3
            - zone_id: 5
              duration: "00:12"
              #repeat: 2
            ##            - zone_id: 6
            ##              duration: "00:05"
            ##              #repeat: 2
            - zone_id: 7
              duration: "00:12"
              #repeat: 3
            - zone_id: 8
              duration: "00:17"
              #repeat: 3
            # Session 3
            ##            - zone_id: 4
            ##              duration: "00:07"
            ##              #repeat: 3
            ##- zone_id: 8
            ##  duration: "00:17"
            ##  #repeat: 3
            ##- zone_id: 7
            ##  duration: "00:12"
            ##  #repeat: 3
    - name: "Water_drop_1"
      enabled: true
      entity_id: "switch.tasmota3_1" # main valve
      all_zones_config: # <= Add these three lines <─┐
        show: # <= to the configuration            <─┤
          timeline: true # <= for all zones        <─┘
      preamble: "00:01"
      zones:
        #- zone_id: 1
        - name: "Wattering Trees"
          entity_id: "switch.tasmota1_1"
        - name: "Wattering Trees & Bushes"
          entity_id: "switch.tasmota1_4"
        - name: "Wattering  Bushes"
          entity_id: "switch.tasmota2_2"
      sequences:
        - name: "Sequences_water_drop"
          delay: "00:01"
          enabled: true
          #  repeat: 2
          schedules:
            #- time: "05:00" #- for 5 AM
            time:
              sun: "sunset"
              after: "00:10"
            anchor: finish
            day:
              every_n_days: 2
              start_n_days: 2023-05-14 # Starting date + 1
          zones:
            - zone_id: [3]
              duration: "00:30"
            - zone_id: [2]
              duration: "01:00"
    - name: "Water_drop_2"
      enabled: true
      entity_id: "switch.tasmota3_1" # main valve
      all_zones_config: # <= Add these three lines <─┐
        show: # <= to the configuration            <─┤
          timeline: true # <= for all zones        <─┘
      preamble: "00:01"
      zones:
        #- zone_id: 1
        - name: "Wattering Trees"
          entity_id: "switch.tasmota1_1"
        - name: "Wattering Trees & Bushes"
          entity_id: "switch.tasmota1_4"
        - name: "Wattering  Bushes"
          entity_id: "switch.tasmota2_2"
      sequences:
        - name: "Sequences_water_drop"
          delay: "00:01"
          enabled: true
          #  repeat: 2
          schedules:
            #- time: "05:00" #- for 5 AM
            time:
              sun: "sunset"
              after: "00:10"
            anchor: finish
            day:
              every_n_days: 2
              start_n_days: 2023-05-13 # Starting date + 1
          zones:
            - zone_id: [3]
              duration: "00:30"
            - zone_id: 1
              duration: "01:00"
    - name: "Grass Manual"
      enabled: true
      entity_id: "switch.tasmota3_1" # main valve
      all_zones_config: # <= Add these three lines <─┐
        show: # <= to the configuration            <─┤
          timeline: true # <= for all zones        <─┘
      preamble: "00:01"
      zones:
        #- zone_id: 1
        - name: "Watering_right1"
          entity_id: "switch.tasmota1_3"
        - name: "Watering_right2"
          entity_id: "switch.tasmota1_2"
        - name: "Watering_drop_fruts"
          entity_id: "switch.tasmota1_1"
        - name: "Watering_drop_back"
          entity_id: "switch.tasmota1_4"
        - name: "Watering_front"
          entity_id: "switch.tasmota2_1"
        - name: "Watering_drop_left"
          entity_id: "switch.tasmota2_2"
        - name: "Watering_back1"
          entity_id: "switch.tasmota2_3"
        - name: "Watering_back2"
          entity_id: "switch.tasmota2_4"
      sequences:
        - name: "Sequences_evening"
          delay: "00:01"
          enabled: true
          #  repeat: 2
          #schedules:
            #    start_n_days: now()
            #    every_n_days: 4
            #- time: "05:00" - for 5 AM
            #time:
            #  sun: "sunset"
            #  after: "00:15"
            #day:
            #  every_n_days: 1
            #  start_n_days: 2023-05-13 # Starting date + 1
          zones:
            # Session 1
            - zone_id: 1
              duration: "00:09"
              #repeat: 2
            - zone_id: 2
              duration: "00:09"
              #repeat: 2
            ##            - zone_id: [3,6]
            ##              duration: "00:10"
            #repeat: 2
            ##            - zone_id: 4
            ##              duration: "00:10"
            #repeat: 3
            - zone_id: 5
              duration: "00:12"
              #repeat: 2
            ##            - zone_id: 6
            ##              duration: "00:05"
            ##              #repeat: 2
            - zone_id: 7
              duration: "00:12"
              #repeat: 3
            - zone_id: 8
              duration: "00:17"
              #repeat: 3
            # Session 2
            - zone_id: 1
              duration: "00:09"
              #repeat: 2
            - zone_id: 2
              duration: "00:09"
              #repeat: 2
            ##            - zone_id: [3, 6]
            ##              duration: "00:10"
            ##              #repeat: 2
            ##            - zone_id: 4
            ##              duration: "00:10"
            #repeat: 3
            - zone_id: 5
              duration: "00:12"
              #repeat: 2
            ##            - zone_id: 6
            ##              duration: "00:05"
            ##              #repeat: 2
            - zone_id: 7
              duration: "00:12"
              #repeat: 3
            - zone_id: 8
              duration: "00:17"
              #repeat: 3
            # Session 3
            ##            - zone_id: 4
            ##              duration: "00:07"
            ##              #repeat: 3
            - zone_id: 8
              duration: "00:17"
              #repeat: 3
            - zone_id: 7
              duration: "00:12"
              #repeat: 3
    - name: "Water_drop_manual"
      enabled: true
      entity_id: "switch.tasmota3_1" # main valve
      all_zones_config: # <= Add these three lines <─┐
        show: # <= to the configuration            <─┤
          timeline: true # <= for all zones        <─┘
      preamble: "00:01"
      zones:
        #- zone_id: 1
        - name: "Wattering Trees"
          entity_id: "switch.tasmota1_1"
        - name: "Wattering Trees & Bushes"
          entity_id: "switch.tasmota1_4"
        - name: "Wattering  Bushes"
          entity_id: "switch.tasmota2_2"
      sequences:
        - name: "Sequences_water_drop"
          delay: "00:01"
          enabled: true
          #  repeat: 2
          #schedules:
           #- time: "05:00" #- for 5 AM
           # time:
           #   sun: "sunset"
           #   after: "00:10"
           # anchor: finish
           # day:
            #  every_n_days: 2
            #  start_n_days: 2023-05-14 # Starting date + 1
          zones:
            - zone_id: [3]
              duration: "00:30"
            - zone_id: [1]
              duration: "01:00"
            - zone_id: [2]
              duration: "01:00"              


sensor:
  - platform: average
    name: irrigation_unlimited_rain_1
    entities:
      #- sensor.openweathermap_forecast_precipitation
      - sensor.today_day_precipitation
    precision: 2
    start: "{{ now().replace(hour=0).replace(minute=30).replace(second=0) - timedelta(days=1) }}"
    end: "{{ now().replace(hour=23).replace(minute=59).replace(second=0) - timedelta(days=1) }}"
    scan_interval: 600







